# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('response', models.TextField(max_length=255, verbose_name='Reponse')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FAQ', to='faq.Category', verbose_name='Categories')),
            ],
            options={
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
