# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Activer'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='response',
            field=models.TextField(verbose_name='Reponse'),
        ),
    ]
