# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('subTitle', models.CharField(max_length=255, verbose_name='Sous-titre')),
                ('description', models.TextField(verbose_name='Description du projet')),
                ('dateEvent', models.DateTimeField(verbose_name="Date de l'evenement")),
                ('location', models.CharField(max_length=255, verbose_name='Lieu')),
                ('logo', models.ImageField(blank=True, upload_to='avatars_projects', verbose_name='Logo')),
            ],
            options={
                'verbose_name_plural': 'events',
            },
        ),
    ]
