# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 15:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEvent', models.DateField(verbose_name="Date de l'evenement")),
            ],
            options={
                'verbose_name_plural': 'dateEvents',
            },
        ),
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TimeField(default=datetime.datetime(2016, 8, 22, 15, 43, 51, 679856, tzinfo=utc), verbose_name='Heure'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='dateEvent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.DateEvents', verbose_name='Date'),
        ),
    ]
