# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20160822_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Activer'),
        ),
        migrations.AlterField(
            model_name='dateevents',
            name='dateEvent',
            field=models.DateField(unique=True, verbose_name="Date de l'evenement"),
        ),
    ]
