# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20160822_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='time',
        ),
        migrations.AlterField(
            model_name='events',
            name='dateEvent',
            field=models.DateField(unique=True, verbose_name="Date de l'evenement"),
        ),
        migrations.AlterField(
            model_name='events',
            name='logo',
            field=models.ImageField(blank=True, upload_to='avatars_events', verbose_name='Logo'),
        ),
        migrations.DeleteModel(
            name='DateEvents',
        ),
    ]
