# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20160822_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='dateEvent',
            field=models.DateTimeField(unique=True, verbose_name="Date de l'evenement"),
        ),
    ]
