# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20160822_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time',
            field=models.TimeField(default='00:00:00', verbose_name='Heure'),
        ),
        migrations.AlterField(
            model_name='events',
            name='dateEvent',
            field=models.DateField(unique=True, verbose_name="Date de l'evenement"),
        ),
    ]
