# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20160822_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='dateEvent',
            field=models.DateField(verbose_name="Date de l'evenement"),
        ),
    ]
