# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-24 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20160824_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='url',
            field=models.URLField(blank=True, max_length=255, verbose_name='URL'),
        ),
    ]
