# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_events_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='name_url',
            field=models.CharField(default='EventBrite', max_length=255, verbose_name="Nom de l'url"),
        ),
        migrations.AlterField(
            model_name='events',
            name='url',
            field=models.URLField(max_length=255, verbose_name='URL'),
        ),
    ]
