# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 12:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20160826_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='name_url',
            field=models.CharField(default='Inscrit-toi', max_length=255, verbose_name="Nom de l'url"),
        ),
    ]
