# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-29 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20160826_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='name_url',
        ),
    ]
