# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_events_name_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='thanking_picture',
            field=models.ImageField(blank=True, upload_to='avatars_events', verbose_name='Thanking picture'),
        ),
        migrations.AddField(
            model_name='events',
            name='thanking_text',
            field=models.TextField(default='Merci a nos partenaires pour leur soutien', verbose_name='Texte de remerciment des partenaires.'),
            preserve_default=False,
        ),
    ]
