# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20160913_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='events',
            name='thanking_picture',
        ),
        migrations.AddField(
            model_name='events',
            name='fisrt_rigth_picture',
            field=models.ImageField(blank=True, upload_to='avatars_events', verbose_name='First rigth picture'),
        ),
        migrations.AddField(
            model_name='events',
            name='presenter_picture',
            field=models.ImageField(blank=True, upload_to='avatars_events', verbose_name='Presenter picture'),
        ),
        migrations.AddField(
            model_name='events',
            name='second_rigth_picture',
            field=models.ImageField(blank=True, upload_to='avatars_events', verbose_name='Second rigth picture'),
        ),
    ]
