# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20160914_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='presenter_picture',
            field=models.ImageField(upload_to='avatars_events', verbose_name='Presenter picture'),
        ),
    ]
