# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20160914_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='fisrt_rigth_picture',
        ),
        migrations.RemoveField(
            model_name='events',
            name='second_rigth_picture',
        ),
        migrations.AddField(
            model_name='events',
            name='fisrt_right_picture',
            field=models.ImageField(blank=True, upload_to='avatars_events', verbose_name='First right picture'),
        ),
        migrations.AddField(
            model_name='events',
            name='second_right_picture',
            field=models.ImageField(blank=True, upload_to='avatars_events', verbose_name='Second right picture'),
        ),
    ]
