# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20160914_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='fisrt_right_picture',
            new_name='first_right_picture',
        ),
    ]
